name: terraform-check

on:
  push:
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform.yml'

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/docker-nginx

    steps:
      - name: コードを取得
        uses: actions/checkout@v4

      - name: Terraform を準備
        uses: hashicorp/setup-terraform@v3

      - name: 書式チェック
        run: terraform fmt -check

      - name: 初期化
        run: terraform init -backend=false

      - name: 文法チェック
        run: terraform validate

  
  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: nginx イメージの脆弱性スキャン
        run: |
          docker run --rm aquasec/trivy:0.69.3 image \
            --severity HIGH,CRITICAL \
            --exit-code 0 \
            nginx:alpine
